### ISSUE TITLE
一直在"开启快速去色"

### ISSUE THREAD

**Issue by yangzeon** [liasica/JiaGuoMengTrainer#1]
分辨率540*960
夜神模拟器+按键精灵手机助手

没改任何东西.直接调试.
您的脚本在运行过程中产生如下信息：
当前脚本第6行：开启快速取色

然后就一直在这了...请问后面怎么做...

**Comment by liasica** [comment]
没问题~~~只有火车来了才会有继续的输出...

收金币和其他操作我没有做输出好像, 你可以断点看下
