### ISSUE TITLE
正式版没有火车的时候不收金且会重启

### ISSUE THREAD

**Issue by huangxb1991** [liasica/JiaGuoMengTrainer#22]
我两个模拟器都是这样，今天更新后发现没有火车的时候不会收金币而且隔一段时间还会自动杀进程重启

**Comment by liasica** [comment]
> 我两个模拟器都是这样，今天更新后发现没有火车的时候不会收金币而且隔一段时间还会自动杀进程重启

方便远程下调试下吗? 因为我测试了下没有发现这个问题. 脚本版本号是多少?

**Comment by huangxb1991** [comment]
![image](https://user-images.githubusercontent.com/7222277/66250268-0f921d00-e773-11e9-922d-b2f6e41561d4.png)
1.02   @@1.03都试过都是一样
@liasica 
好像是我分辨率搞错了？🤦‍

**Comment by huangxb1991** [comment]
> > 我两个模拟器都是这样，今天更新后发现没有火车的时候不会收金币而且隔一段时间还会自动杀进程重启
> 
> 方便远程下调试下吗? 因为我测试了下没有发现这个问题. 脚本版本号是多少?

试了1920x1080也是一样不收金
![image](https://user-images.githubusercontent.com/7222277/66250403-dc508d80-e774-11e9-9f81-b12a1fd9816b.png)这是按键精灵版本

**Comment by liasica** [comment]
> > > 我两个模拟器都是这样，今天更新后发现没有火车的时候不会收金币而且隔一段时间还会自动杀进程重启
> > 
> > 
> > 方便远程下调试下吗? 因为我测试了下没有发现这个问题. 脚本版本号是多少?
> 
> 试了1920x1080也是一样不收金
> ![image](https://user-images.githubusercontent.com/7222277/66250403-dc508d80-e774-11e9-9f81-b12a1fd9816b.png)这是按键精灵版本

微信: magicrolan

下载安装anydesk 然后我远程你调试下~
