### ISSUE TITLE
疑问：选用断网来跳火车时会重复三次

### ISSUE THREAD

**Issue by y2o3** [liasica/JiaGuoMengTrainer#23]
发现有不要的货物时会重复三次弹出->飞行模式->联网->回到游戏（没有点击任何位置，因为没有断线重连的标记）->弹出 的过程，然后才会点击然后继续运行，请问是bug还是设定是这样的

**Comment by y2o3** [comment]
注：不是三次是随机多次重启，，
远古的0.10版本并没有这个bug

**Comment by liasica** [comment]
分辨率多少?

**Comment by sonicfire** [comment]
今早我已经反馈过这个问题，分辨率1080*1920

**Comment by liasica** [comment]
没明白是什么意思

重复三次的原因是因为会有误判的可能性, 三次能保证误判率比较小.

**Comment by y2o3** [comment]
正常原来的代码是直接按下home键，然后会回到主界面，开启关闭飞行模式然后回到游戏
新版会在回到有以后直接再次按下home键回到主界面重新开启关闭飞行模式再回到游戏
重复几次后才会收金币等操作
猜测是由于某个地方缺少delay
没有跳出判定或者由于刚刚打开游戏时火车还在还没有更新界面导致重新判定有货物没有送走然后再次跳到开飞行的地方

**Comment by liasica** [comment]
> 正常原来的代码是直接按下home键，然后会回到主界面，开启关闭飞行模式然后回到游戏
> 新版会在回到有以后直接再次按下home键回到主界面重新开启关闭飞行模式再回到游戏
> 重复几次后才会收金币等操作
> 猜测是由于某个地方缺少delay
> 没有跳出判定或者由于刚刚打开游戏时火车还在还没有更新界面导致重新判定有货物没有送走然后再次跳到开飞行的地方

试下1.05-fix

**Comment by y2o3** [comment]
木得问题了~~

**Comment by liasica** [comment]
ok
