### ISSUE TITLE
1.5版脚本语法出错

### ISSUE THREAD

**Issue by BackTrackCRoot** [liasica/JiaGuoMengTrainer#27]
最新版的一个函数 出错do while 里多写了一个end sub  在loop之前 导致其中一个if语句失效 整体脚本不可运行 删除loop 前的end sub 即可。

另外 题外话 为啥我运行了一下 用mumu 没有收金币啥的反应 只有自动关窗口 难道我的操作用问题

**Comment by liasica** [comment]
> 最新版的一个函数 出错do while 里多写了一个end sub 在loop之前 导致其中一个if语句失效 整体脚本不可运行 删除loop 前的end sub 即可。
> 
> 另外 题外话 为啥我运行了一下 用mumu 没有收金币啥的反应 只有自动关窗口 难道我的操作用问题

1.0.5-fix已经修了吧~ 你试试

这语法真是令人蛋疼

**Comment by BackTrackCRoot** [comment]
Thanks
