### ISSUE TITLE
大佬，游戏版本更新啦，求更新4个新橙建筑啊~完全不会自己改

### ISSUE THREAD

**Issue by whitezoe12** [liasica/JiaGuoMengTrainer#33]
大佬，知道你最近在忙高科技。。。能否抽空更新一下新版本橙色建筑？（不然收货真的尴尬）
其他人的脚本不喜欢，不想换，还是你的稳定高效啊！
等个更新~先谢谢大佬了！

**Comment by liasica** [comment]
可以手动选择的哈。

**Comment by liasica** [comment]
你使用的版本是什么？

**Comment by whitezoe12** [comment]
V1.05，强国煤业，我手动选择了相应的位置序号，但是他货物点了就是不拉过去，然后直接重启刷新火车。。。

**Comment by liasica** [comment]
> V1.05，强国煤业，我手动选择了相应的位置序号，但是他货物点了就是不拉过去，然后直接重启刷新火车。。。

应该是没问题的，你多观察下，我今晚测试下

**Comment by whitezoe12** [comment]
> > V1.05，强国煤业，我手动选择了相应的位置序号，但是他货物点了就是不拉过去，然后直接重启刷新火车。。。
> 
> 应该是没问题的，你多观察下，我今晚测试下

好的，0点我再观察测试下，麻烦大佬了！

**Comment by whitezoe12** [comment]
> > V1.05，强国煤业，我手动选择了相应的位置序号，但是他货物点了就是不拉过去，然后直接重启刷新火车。。。
> 
> 应该是没问题的，你多观察下，我今晚测试下

大佬，已再次测试，强国煤业不拉货，其他新橙未测试。

**Comment by whitezoe12** [comment]
不能上煤业，为了堆供货的话，目前只能4橙，要拉很久很久 = =

**Comment by liasica** [comment]
> 不能上煤业，为了堆供货的话，目前只能4橙，要拉很久很久 = =

我测试了下没问题的，拉货和建筑是什么无关，只和建筑位置有关

**Comment by whitezoe12** [comment]
是的，原理我知道，我现在问题是我设置8号收货，其他如企鹅收货的，换成煤业就是不拉过去？

**Comment by liasica** [comment]
试试更换个位置

**Comment by whitezoe12** [comment]
> 试试更换个位置

好的，我印象中7和8都试过，今晚我再试试吧

**Comment by whitezoe12** [comment]
> 试试更换个位置

换了7号位置，成功，不知道什么原因之前不行，其他位置我就不测试了~ 感谢大佬回复，晚安！
