### ISSUE TITLE
mumu模拟器 运行脚本无响应

### ISSUE THREAD

**Issue by Tang-DJ** [liasica/JiaGuoMengTrainer#6]
环境：mumu模拟器mac版，分辨率540 × 960
情况： 
1.加载云脚本至本地，配置一个升级建筑。
2.点击运行，显示'开始运行'，显示'音量键控制开关'，显示'结束运行'。
3.尝试关闭音量键控制，点击运行，显示'开始运行'，后无响应。
4.实测运行脚本皆不行。本地录制脚本运行即可。
尝试： 自己录制脚本，可以运行。

**Comment by liasica** [comment]
建议使用雷电

**Comment by liasica** [comment]
截图附带模拟器分辨率配置和脚本配置，查看循环是否设置正确

**Comment by Tang-DJ** [comment]
雷电模拟器无mac版，无法更换模拟器
经过测试，按键精灵降低至3.1.7版本可正常运行，但是momo模拟器宽度最低720无法适配脚本。
绝望.jpg

**Comment by MegaWeed** [comment]
我夜神会有个浮窗挡在界面 脚本会点浮窗然后停止运行 隐藏浮窗试试
